"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import {
  AlertTriangle,
  CheckCircle2,
  ImagePlus,
  Loader2,
  RefreshCw,
  ScanEye,
  ShieldCheck,
  Upload,
  XCircle,
  Sparkles,
  Camera,
  Zap,
  Info,
} from "lucide-react";

const GENERATORS = [
  { id: "gemini", name: "Gemini / Imagen", color: "#4285f4", icon: "✦" },
  { id: "dalle", name: "DALL-E / ChatGPT", color: "#10a37f", icon: "◆" },
  { id: "midjourney", name: "Midjourney", color: "#5865f2", icon: "▲" },
  { id: "stable_diffusion", name: "Stable Diffusion", color: "#a855f7", icon: "●" },
  { id: "firefly", name: "Adobe Firefly", color: "#ff6b35", icon: "★" },
  { id: "flux", name: "Flux", color: "#f59e0b", icon: "◇" },
  { id: "leonardo", name: "Leonardo AI", color: "#ec4899", icon: "◎" },
];

const ANALYSIS_METHODS = [
  { id: "metadata", label: "Metadata Scan", icon: "🔍", weight: 15, desc: "EXIF, XMP, C2PA, AI watermarks" },
  { id: "frequency", label: "Frequency Analysis", icon: "📊", weight: 18, desc: "FFT spectral patterns, energy distribution" },
  { id: "color", label: "Color Distribution", icon: "🎨", weight: 25, desc: "Histogram smoothness, saturation, channel correlation" },
  { id: "noise", label: "Noise Patterns", icon: "📡", weight: 12, desc: "Sensor noise vs synthetic noise" },
  { id: "edge", label: "Edge Coherence", icon: "🔲", weight: 12, desc: "Edge transitions, sharpness uniformity" },
  { id: "texture", label: "Texture Complexity", icon: "🧬", weight: 18, desc: "LBP micro-texture, repetition patterns" },
];

function loadImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}

function getImageData(img, maxSize = 512) {
  const canvas = document.createElement("canvas");
  let { width, height } = img;
  if (width > maxSize || height > maxSize) {
    const scale = maxSize / Math.max(width, height);
    width = Math.round(width * scale);
    height = Math.round(height * scale);
  }
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext("2d");
  ctx.drawImage(img, 0, 0, width, height);
  return ctx.getImageData(0, 0, width, height);
}

function getGrayscale(data, w, h) {
  const gray = new Float32Array(w * h);
  for (let i = 0; i < w * h; i++) {
    gray[i] = 0.299 * data[i * 4] + 0.587 * data[i * 4 + 1] + 0.114 * data[i * 4 + 2];
  }
  return gray;
}

function searchBytesForPatterns(buffer) {
  const bytes = new Uint8Array(buffer);
  let text = "";
  for (let i = 0; i < bytes.length; i++) {
    text += String.fromCharCode(bytes[i]);
  }
  const lower = text.toLowerCase();

  const patterns = {
    gemini: ["gemini", "imagen", "google ai", "deepmind", "synthid", "google cloud"],
    dalle: ["dall-e", "dalle", "openai", "chatgpt"],
    midjourney: ["midjourney", "mj-v", "mj:v"],
    stable_diffusion: ["stable diffusion", "stablediffusion", "stability ai", "comfyui", "automatic1111"],
    firefly: ["firefly", "adobe", "content credentials"],
    flux: ["flux", "black forest", "bfl"],
    leonardo: ["leonardo", "leonardo.ai"],
  };

  const found = {};
  for (const [gen, pats] of Object.entries(patterns)) {
    for (const p of pats) {
      if (lower.includes(p)) {
        if (!found[gen]) found[gen] = [];
        found[gen].push(p);
      }
    }
  }

  const hasC2PA = lower.includes("c2pa") || lower.includes("content credentials") || lower.includes("claim");
  const hasExifAI = lower.includes("ai-generated") || lower.includes("generated by") || lower.includes("synthid") || lower.includes("watermark");

  return { found, hasC2PA, hasExifAI };
}

async function analyzeFileMetadata(file) {
  return new Promise((resolve) => {
    if (!file || file.size === 0) {
      resolve({ generatorHits: {}, hasC2PA: false, hasExifAI: false, score: 0 });
      return;
    }

    const slice = file.slice(0, 256 * 1024);
    const reader = new FileReader();
    reader.onload = () => {
      const result = searchBytesForPatterns(reader.result);
      let score = 0;
      const generatorHits = {};

      for (const [gen, hits] of Object.entries(result.found)) {
        generatorHits[gen] = hits;
        score = Math.max(score, 90);
      }

      if (result.hasC2PA) score = Math.max(score, 75);
      if (result.hasExifAI) score = Math.max(score, 70);

      resolve({ generatorHits, hasC2PA: result.hasC2PA, hasExifAI: result.hasExifAI, score });
    };
    reader.onerror = () => resolve({ generatorHits: {}, hasC2PA: false, hasExifAI: false, score: 0 });
    reader.readAsArrayBuffer(slice);
  });
}

function detectMetadata(img, file) {
  let score = 0;
  let found = [];
  let generatorHits = {};

  const src = (img.src || "").toLowerCase();
  const urlPatterns = [
    { gen: "dalle", patterns: ["dall-e", "dalle", "openai"] },
    { gen: "midjourney", patterns: ["midjourney", "cdn.midjourney"] },
    { gen: "stable_diffusion", patterns: ["stablediffusion", "stable-diffusion", "civitai"] },
    { gen: "gemini", patterns: ["gemini", "google", "imagen"] },
    { gen: "firefly", patterns: ["firefly", "adobe"] },
  ];

  for (const { gen, patterns } of urlPatterns) {
    for (const p of patterns) {
      if (src.includes(p)) {
        score = 85;
        if (!generatorHits[gen]) generatorHits[gen] = [];
        generatorHits[gen].push(`url:${p}`);
      }
    }
  }

  if (file) {
    try {
      const allFound = Object.keys(generatorHits).length > 0 ? generatorHits : {};
      const urlHits = { ...generatorHits };
      for (const [gen, hits] of Object.entries(urlHits)) {
        if (!allFound[gen]) allFound[gen] = [];
        allFound[gen].push(...hits);
      }
    } catch {}
  }

  const allFoundGenerators = Object.keys(generatorHits);
  if (allFoundGenerators.length > 0) {
    found.push(...allFoundGenerators.map((g) => `generator:${g}`));
  }

  return { score: Math.min(score, 100), found, generatorHits };
}

function detectFrequency(gray, w, h) {
  const blockSize = Math.min(64, w, h);
  const blocksX = Math.floor(w / blockSize);
  const blocksY = Math.floor(h / blockSize);
  if (blocksX < 2 || blocksY < 2) return { score: 30, details: "Image too small" };

  let highFreqEnergy = 0;
  let lowFreqEnergy = 0;
  let blockVariances = [];

  for (let by = 0; by < blocksY - 1; by++) {
    for (let bx = 0; bx < blocksX - 1; bx++) {
      const block = [];
      for (let y = 0; y < blockSize; y++) {
        for (let x = 0; x < blockSize; x++) {
          block.push(gray[(by * blockSize + y) * w + (bx * blockSize + x)]);
        }
      }
      const mean = block.reduce((a, b) => a + b, 0) / block.length;
      let variance = 0;
      for (const v of block) variance += (v - mean) ** 2;
      blockVariances.push(variance / block.length);

      const half = Math.floor(block.length / 2);
      let lf = 0;
      let hf = 0;
      for (let i = 0; i < half; i++) lf += block[i] ** 2;
      for (let i = half; i < block.length; i++) hf += block[i] ** 2;
      lowFreqEnergy += lf;
      highFreqEnergy += hf;
    }
  }

  const avgVar = blockVariances.reduce((a, b) => a + b, 0) / blockVariances.length;
  const varStd = Math.sqrt(blockVariances.reduce((a, b) => a + (b - avgVar) ** 2, 0) / blockVariances.length);
  const lowHighRatio = lowFreqEnergy > 0 ? highFreqEnergy / lowFreqEnergy : 0;

  let score = 30;

  if (lowHighRatio < 0.15) score += 35;
  else if (lowHighRatio < 0.3) score += 25;
  else if (lowHighRatio < 0.5) score += 15;
  else if (lowHighRatio < 0.7) score += 5;
  else if (lowHighRatio > 1.2) score -= 25;
  else if (lowHighRatio > 0.9) score -= 15;

  const varCoeff = avgVar > 0 ? varStd / avgVar : 0;
  if (varCoeff < 0.25) score += 20;
  else if (varCoeff < 0.45) score += 12;
  else if (varCoeff > 1.2) score -= 12;

  score = Math.max(0, Math.min(100, score));
  return { score, details: `LF/HF: ${lowHighRatio.toFixed(3)}, Var CV: ${varCoeff.toFixed(3)}` };
}

function detectColor(data, w, h) {
  const rHist = new Uint32Array(256);
  const gHist = new Uint32Array(256);
  const bHist = new Uint32Array(256);
  const total = w * h;

  for (let i = 0; i < total; i++) {
    rHist[data[i * 4]]++;
    gHist[data[i * 4 + 1]]++;
    bHist[data[i * 4 + 2]]++;
  }

  function smoothness(hist) {
    let diff = 0;
    for (let i = 1; i < 256; i++) diff += Math.abs(hist[i] - hist[i - 1]);
    return diff / (total * 255);
  }

  const avgSmooth = (smoothness(rHist) + smoothness(gHist) + smoothness(bHist)) / 3;

  let totalSat = 0;
  let veryHighSat = 0;
  for (let i = 0; i < total; i++) {
    const r = data[i * 4] / 255;
    const g = data[i * 4 + 1] / 255;
    const b = data[i * 4 + 2] / 255;
    const max = Math.max(r, g, b);
    const min = Math.min(r, g, b);
    const sat = max === 0 ? 0 : (max - min) / max;
    totalSat += sat;
    if (sat > 0.85) veryHighSat++;
  }
  const avgSat = totalSat / total;
  const veryHighSatRatio = veryHighSat / total;

  let channelDiff = 0;
  for (let i = 0; i < 256; i++) {
    channelDiff += Math.abs(rHist[i] - gHist[i]) + Math.abs(gHist[i] - bHist[i]);
  }
  const channelSim = 1 - channelDiff / (256 * total * 2);

  let score = 30;

  if (avgSmooth < 0.01) score += 35;
  else if (avgSmooth < 0.02) score += 28;
  else if (avgSmooth < 0.035) score += 20;
  else if (avgSmooth < 0.05) score += 10;
  else if (avgSmooth > 0.1) score -= 15;

  if (avgSat > 0.5) score += 20;
  else if (avgSat > 0.35) score += 12;
  else if (avgSat < 0.1) score -= 5;

  if (veryHighSatRatio > 0.1) score += 12;
  else if (veryHighSatRatio > 0.05) score += 6;

  if (channelSim > 0.9) score += 12;
  else if (channelSim > 0.8) score += 6;

  score = Math.max(0, Math.min(100, score));
  return { score, details: `Smooth: ${avgSmooth.toFixed(4)}, Sat: ${avgSat.toFixed(3)}, ChSim: ${channelSim.toFixed(3)}` };
}

function detectNoise(gray, w, h) {
  const blockSize = 8;
  const blocksX = Math.floor(w / blockSize);
  const blocksY = Math.floor(h / blockSize);
  if (blocksX < 3 || blocksY < 3) return { score: 30, details: "Image too small" };

  const blockVars = [];
  for (let by = 0; by < blocksY; by++) {
    for (let bx = 0; bx < blocksX; bx++) {
      const block = [];
      for (let y = 0; y < blockSize; y++) {
        for (let x = 0; x < blockSize; x++) {
          block.push(gray[(by * blockSize + y) * w + (bx * blockSize + x)]);
        }
      }
      const mean = block.reduce((a, b) => a + b, 0) / block.length;
      let variance = 0;
      for (const v of block) variance += (v - mean) ** 2;
      blockVars.push(variance / block.length);
    }
  }

  const avgVar = blockVars.reduce((a, b) => a + b, 0) / blockVars.length;
  const stdVar = Math.sqrt(blockVars.reduce((a, b) => a + (b - avgVar) ** 2, 0) / blockVars.length);

  let gradientDiffs = [];
  for (let by = 0; by < blocksY; by++) {
    for (let bx = 0; bx < blocksX - 1; bx++) {
      const idx = by * blocksX + bx;
      gradientDiffs.push(Math.abs(blockVars[idx] - blockVars[idx + 1]));
    }
  }
  const avgGrad = gradientDiffs.length > 0 ? gradientDiffs.reduce((a, b) => a + b, 0) / gradientDiffs.length : 0;

  const varCoeff = avgVar > 0 ? stdVar / avgVar : 0;

  let score = 30;

  if (avgVar < 8) score += 35;
  else if (avgVar < 25) score += 28;
  else if (avgVar < 60) score += 15;
  else if (avgVar < 150) score += 0;
  else if (avgVar > 400) score -= 25;
  else if (avgVar > 200) score -= 15;
  else if (avgVar > 100) score -= 8;

  if (varCoeff < 0.25) score += 18;
  else if (varCoeff < 0.5) score += 10;
  else if (varCoeff > 1.2) score -= 8;

  if (avgGrad < 1.5) score += 12;
  else if (avgGrad < 5) score += 6;

  score = Math.max(0, Math.min(100, score));
  return { score, details: `Avg noise: ${avgVar.toFixed(1)}, Noise CV: ${varCoeff.toFixed(3)}` };
}

function detectEdges(gray, w, h) {
  const edges = new Float32Array(w * h);
  for (let y = 1; y < h - 1; y++) {
    for (let x = 1; x < w - 1; x++) {
      const idx = y * w + x;
      const gx = -gray[(y - 1) * w + (x - 1)] + gray[(y - 1) * w + (x + 1)] + -2 * gray[y * w + (x - 1)] + 2 * gray[y * w + (x + 1)] + -gray[(y + 1) * w + (x - 1)] + gray[(y + 1) * w + (x + 1)];
      const gy = -gray[(y - 1) * w + (x - 1)] + -2 * gray[(y - 1) * w + x] + -gray[(y - 1) * w + (x + 1)] + gray[(y + 1) * w + (x - 1)] + 2 * gray[(y + 1) * w + x] + gray[(y + 1) * w + (x + 1)];
      edges[idx] = Math.sqrt(gx * gx + gy * gy);
    }
  }

  let edgeCount = 0;
  let maxEdge = 0;
  let edgeVals = [];
  for (let i = 0; i < edges.length; i++) {
    if (edges[i] > 20) {
      edgeCount++;
      edgeVals.push(edges[i]);
      maxEdge = Math.max(maxEdge, edges[i]);
    }
  }

  const edgeRatio = edgeCount / (w * h);

  let edgeMAD = 0;
  if (edgeVals.length > 10) {
    edgeVals.sort((a, b) => a - b);
    const median = edgeVals[Math.floor(edgeVals.length / 2)];
    edgeMAD = edgeVals.reduce((sum, v) => sum + Math.abs(v - median), 0) / edgeVals.length;
  }

  let score = 30;

  if (edgeRatio < 0.02) score += 30;
  else if (edgeRatio < 0.06) score += 22;
  else if (edgeRatio < 0.12) score += 12;
  else if (edgeRatio < 0.2) score += 4;
  else if (edgeRatio > 0.5) score -= 20;
  else if (edgeRatio > 0.35) score -= 12;
  else if (edgeRatio > 0.25) score -= 6;

  if (edgeMAD < 10) score += 22;
  else if (edgeMAD < 25) score += 14;
  else if (edgeMAD < 45) score += 6;
  else if (edgeMAD > 80) score -= 10;

  if (maxEdge < 120) score += 12;
  else if (maxEdge < 200) score += 6;

  score = Math.max(0, Math.min(100, score));
  return { score, details: `Edge ratio: ${(edgeRatio * 100).toFixed(1)}%, Edge MAD: ${edgeMAD.toFixed(1)}` };
}

function detectTexture(gray, w, h) {
  const blockSize = 16;
  const blocksX = Math.floor(w / blockSize);
  const blocksY = Math.floor(h / blockSize);
  if (blocksX < 2 || blocksY < 2) return { score: 30, details: "Image too small" };

  const lbpHistograms = [];
  for (let by = 0; by < blocksY; by++) {
    for (let bx = 0; bx < blocksX; bx++) {
      const hist = new Float32Array(256);
      let count = 0;
      for (let y = 1; y < blockSize - 1; y++) {
        for (let x = 1; x < blockSize - 1; x++) {
          const cy = by * blockSize + y;
          const cx = bx * blockSize + x;
          const center = gray[cy * w + cx];
          let code = 0;
          if (gray[(cy - 1) * w + (cx - 1)] >= center) code |= 128;
          if (gray[(cy - 1) * w + cx] >= center) code |= 64;
          if (gray[(cy - 1) * w + (cx + 1)] >= center) code |= 32;
          if (gray[cy * w + (cx + 1)] >= center) code |= 16;
          if (gray[(cy + 1) * w + (cx + 1)] >= center) code |= 8;
          if (gray[(cy + 1) * w + cx] >= center) code |= 4;
          if (gray[(cy + 1) * w + (cx - 1)] >= center) code |= 2;
          if (gray[cy * w + (cx - 1)] >= center) code |= 1;
          hist[code]++;
          count++;
        }
      }
      if (count > 0) for (let i = 0; i < 256; i++) hist[i] /= count;
      lbpHistograms.push(hist);
    }
  }

  let totalSimilarity = 0;
  let pairCount = 0;
  for (let i = 0; i < lbpHistograms.length; i++) {
    for (let j = i + 1; j < Math.min(i + 4, lbpHistograms.length); j++) {
      let intersection = 0;
      for (let k = 0; k < 256; k++) {
        intersection += Math.min(lbpHistograms[i][k], lbpHistograms[j][k]);
      }
      totalSimilarity += intersection;
      pairCount++;
    }
  }
  const avgSimilarity = pairCount > 0 ? totalSimilarity / pairCount : 0;

  let uniformBlocks = 0;
  for (let i = 0; i < lbpHistograms.length; i++) {
    let entropy = 0;
    for (let k = 0; k < 256; k++) {
      if (lbpHistograms[i][k] > 0) entropy -= lbpHistograms[i][k] * Math.log2(lbpHistograms[i][k]);
    }
    if (entropy < 2.0) uniformBlocks++;
  }
  const uniformRatio = uniformBlocks / lbpHistograms.length;

  let score = 30;

  if (avgSimilarity > 0.92) score += 32;
  else if (avgSimilarity > 0.8) score += 22;
  else if (avgSimilarity > 0.65) score += 12;
  else if (avgSimilarity < 0.35) score -= 12;

  if (uniformRatio > 0.5) score += 18;
  else if (uniformRatio > 0.3) score += 10;
  else if (uniformRatio > 0.15) score += 4;

  score = Math.max(0, Math.min(100, score));
  return { score, details: `Block sim: ${avgSimilarity.toFixed(3)}, Uniform: ${(uniformRatio * 100).toFixed(1)}%` };
}

function estimateGeneratorScores(results, metadata) {
  const scores = {};
  for (const g of GENERATORS) scores[g.id] = 8;

  if (metadata.generatorHits && Object.keys(metadata.generatorHits).length > 0) {
    for (const [gen] of Object.entries(metadata.generatorHits)) {
      if (scores[gen] !== undefined) scores[gen] = 92;
    }
    for (const g of GENERATORS) {
      if (scores[g.id] < 50) scores[g.id] = Math.max(4, scores[g.id] - 20);
    }
    return scores;
  }

  const { frequency: f, color: c, noise: n, edge: e, texture: t } = results;

  if (c.score > 55 && f.score > 45) {
    scores.midjourney += 22;
    scores.dalle += 18;
    scores.gemini += 15;
  }
  if (f.score > 55 && n.score > 45) {
    scores.stable_diffusion += 20;
    scores.flux += 14;
  }
  if (n.score > 50 && e.score > 45) {
    scores.gemini += 18;
    scores.firefly += 14;
  }
  if (t.score > 55 && c.score > 50) {
    scores.midjourney += 14;
    scores.leonardo += 12;
  }
  if (e.score > 50 && f.score > 40) {
    scores.firefly += 12;
    scores.dalle += 10;
  }
  if (c.score > 65) {
    scores.gemini += 10;
    scores.dalle += 8;
    scores.midjourney += 6;
  }

  for (const g of GENERATORS) {
    scores[g.id] = Math.min(92, Math.max(3, scores[g.id]));
  }

  return scores;
}

function calculateOverallScore(results) {
  const { metadata: m, frequency: f, color: c, noise: n, edge: e, texture: t } = results;
  const methodScores = [m.score, f.score, c.score, n.score, e.score, t.score];

  const weightedAvg =
    (m.score * 15 + f.score * 18 + c.score * 25 + n.score * 12 + e.score * 12 + t.score * 18) / 100;

  const strongSignals = methodScores.filter((s) => s >= 55).length;
  const veryStrongSignals = methodScores.filter((s) => s >= 70).length;

  let boost = 0;
  if (veryStrongSignals >= 2) boost = 18;
  else if (veryStrongSignals >= 1) boost = 12;
  else if (strongSignals >= 3) boost = 10;
  else if (strongSignals >= 2) boost = 6;

  const maxMethod = Math.max(...methodScores);
  if (maxMethod >= 70) boost += 8;
  else if (maxMethod >= 60) boost += 4;

  const final = Math.min(95, Math.max(5, Math.round(weightedAvg + boost)));
  return final;
}

function GaugeChart({ score }) {
  const radius = 72;
  const stroke = 10;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (score / 100) * circumference;

  const getColor = (s) => {
    if (s >= 70) return { main: "#ef4444", gradient: ["#f87171", "#dc2626"], label: "High" };
    if (s >= 40) return { main: "#f59e0b", gradient: ["#fbbf24", "#d97706"], label: "Medium" };
    return { main: "#22c55e", gradient: ["#4ade80", "#16a34a"], label: "Low" };
  };

  const { main, gradient, label } = getColor(score);
  const gradId = `gauge-grad-${score}`;

  return (
    <div className="relative flex items-center justify-center">
      <svg width="200" height="200" viewBox="0 0 200 200" className="drop-shadow-lg">
        <defs>
          <linearGradient id={gradId} x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor={gradient[0]} />
            <stop offset="100%" stopColor={gradient[1]} />
          </linearGradient>
        </defs>
        <circle cx="100" cy="100" r={radius} fill="none" stroke="#f1f5f9" strokeWidth={stroke + 4} />
        <circle
          cx="100" cy="100" r={radius} fill="none"
          stroke={`url(#${gradId})`} strokeWidth={stroke}
          strokeLinecap="round" strokeDasharray={circumference} strokeDashoffset={offset}
          transform="rotate(-90 100 100)"
          className="transition-all duration-[1200ms] ease-out"
          style={{ filter: `drop-shadow(0 0 6px ${main}40)` }}
        />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="text-5xl font-extrabold tracking-tight" style={{ color: main }}>
          {score}%
        </span>
        <span className="mt-1 text-[10px] font-bold uppercase tracking-[0.2em] text-gray-400">
          AI Probability
        </span>
        <span className="mt-0.5 rounded-full px-2 py-0.5 text-[10px] font-semibold" style={{ backgroundColor: `${main}15`, color: main }}>
          {label} Confidence
        </span>
      </div>
    </div>
  );
}

function AnalysisBar({ method, score, details }) {
  const getBarColor = (s) => {
    if (s >= 60) return "from-red-500 to-rose-500";
    if (s >= 40) return "from-amber-500 to-yellow-500";
    if (s >= 20) return "from-blue-500 to-cyan-500";
    return "from-gray-300 to-gray-400";
  };

  const getTextColor = (s) => {
    if (s >= 60) return "text-red-600";
    if (s >= 40) return "text-amber-600";
    if (s >= 20) return "text-blue-600";
    return "text-gray-500";
  };

  return (
    <div className="group">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-base">{method.icon}</span>
          <span className="text-sm font-medium text-gray-700">{method.label}</span>
        </div>
        <span className={`text-sm font-bold tabular-nums ${getTextColor(score)}`}>{score}%</span>
      </div>
      <div className="mt-1.5 h-2 w-full overflow-hidden rounded-full bg-gray-100">
        <div
          className={`h-full rounded-full bg-gradient-to-r ${getBarColor(score)} transition-all duration-1000 ease-out`}
          style={{ width: `${score}%` }}
        />
      </div>
      <div className="mt-1 flex items-center gap-1 opacity-0 transition-opacity group-hover:opacity-100">
        <Info className="h-3 w-3 text-gray-300" />
        <span className="text-[10px] text-gray-400">{method.desc}</span>
      </div>
      {details && (
        <p className="mt-0.5 text-[10px] font-mono text-gray-400">{details}</p>
      )}
    </div>
  );
}

function GeneratorBar({ gen, score }) {
  return (
    <div className="flex items-center gap-3">
      <div className="flex h-8 w-8 items-center justify-center rounded-lg text-sm font-bold text-white" style={{ backgroundColor: gen.color }}>
        {gen.icon}
      </div>
      <div className="flex-1">
        <div className="flex items-center justify-between">
          <span className="text-sm font-medium text-gray-700">{gen.name}</span>
          <span className="text-xs font-bold text-gray-500">{score}%</span>
        </div>
        <div className="mt-1 h-1.5 w-full overflow-hidden rounded-full bg-gray-100">
          <div
            className="h-full rounded-full transition-all duration-1000 ease-out"
            style={{ width: `${score}%`, backgroundColor: gen.color }}
          />
        </div>
      </div>
    </div>
  );
}

const AiImageDetectorInner = () => {
  const [imageUrl, setImageUrl] = useState(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [results, setResults] = useState(null);
  const [progress, setProgress] = useState(0);
  const [dragActive, setDragActive] = useState(false);
  const fileInputRef = useRef(null);
  const fileRef = useRef(null);

  const handleFile = useCallback((file) => {
    if (!file || !file.type.startsWith("image/")) return;
    setImageUrl(URL.createObjectURL(file));
    fileRef.current = file;
    setResults(null);
    setProgress(0);
  }, []);

  const onDrop = useCallback((e) => {
    e.preventDefault();
    setDragActive(false);
    handleFile(e.dataTransfer?.files?.[0]);
  }, [handleFile]);

  const onDragOver = useCallback((e) => {
    e.preventDefault();
    setDragActive(true);
  }, []);

  const onDragLeave = useCallback(() => setDragActive(false), []);

  const analyze = useCallback(async () => {
    if (!imageUrl) return;
    setAnalyzing(true);
    setProgress(0);

    try {
      const img = await loadImage(imageUrl);
      setProgress(12);
      const { data, width, height } = getImageData(img);
      setProgress(22);
      const gray = getGrayscale(data, width, height);
      setProgress(30);

      let metadata = { score: 0, found: [], generatorHits: {} };
      if (fileRef.current) {
        metadata = await analyzeFileMetadata(fileRef.current);
        const urlMeta = detectMetadata(img, fileRef.current);
        for (const [gen, hits] of Object.entries(urlMeta.generatorHits)) {
          if (!metadata.generatorHits[gen]) metadata.generatorHits[gen] = [];
          metadata.generatorHits[gen].push(...hits);
        }
        if (urlMeta.score > metadata.score) metadata.score = urlMeta.score;
      }
      setProgress(40);

      const frequency = detectFrequency(gray, width, height);
      setProgress(52);
      const color = detectColor(data, width, height);
      setProgress(64);
      const noise = detectNoise(gray, width, height);
      setProgress(76);
      const edge = detectEdges(gray, width, height);
      setProgress(88);
      const texture = detectTexture(gray, width, height);
      setProgress(95);

      const methods = { metadata, frequency, color, noise, edge, texture };
      const overall = calculateOverallScore(methods);
      const generators = estimateGeneratorScores(methods, metadata);

      setResults({ overall, methods, generators });
      setProgress(100);
    } catch {
      setResults(null);
    } finally {
      setAnalyzing(false);
    }
  }, [imageUrl]);

  const reset = useCallback(() => {
    if (imageUrl) URL.revokeObjectURL(imageUrl);
    setImageUrl(null);
    fileRef.current = null;
    setResults(null);
    setProgress(0);
  }, [imageUrl]);

  const sortedGenerators = results
    ? Object.entries(results.generators)
        .sort(([, a], [, b]) => b - a)
        .map(([id, score]) => ({ ...GENERATORS.find((g) => g.id === id), score }))
    : [];

  return (
    <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 md:py-14">
      <div className="overflow-hidden rounded-[2rem] border border-gray-100 bg-white shadow-[0_20px_60px_-15px_rgba(139,92,246,0.15)]">
        {!results ? (
          <div className="p-6 sm:p-10">
            <div
              onDrop={onDrop}
              onDragOver={onDragOver}
              onDragLeave={onDragLeave}
              onClick={() => fileInputRef.current?.click()}
              className={`group relative flex cursor-pointer flex-col items-center justify-center overflow-hidden rounded-2xl border-2 border-dashed p-12 transition-all duration-300 ${
                dragActive
                  ? "border-violet-400 bg-violet-50/80 scale-[1.01]"
                  : "border-gray-200 bg-gradient-to-br from-gray-50/80 to-violet-50/30 hover:border-violet-300 hover:bg-violet-50/50 hover:shadow-lg hover:shadow-violet-100/50"
              }`}
            >
              <div className="absolute inset-0 bg-gradient-to-br from-violet-500/5 to-purple-500/5 opacity-0 transition-opacity group-hover:opacity-100" />

              {imageUrl ? (
                <div className="relative z-10">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={imageUrl} alt="Uploaded preview" className="max-h-80 rounded-xl object-contain shadow-2xl ring-1 ring-black/5" />
                </div>
              ) : (
                <div className="relative z-10 flex flex-col items-center">
                  <div className="relative">
                    <div className="absolute -inset-4 rounded-full bg-gradient-to-r from-violet-500/20 to-purple-500/20 blur-xl transition-opacity group-hover:opacity-100 opacity-0" />
                    <div className="relative flex h-20 w-20 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 to-purple-600 shadow-lg shadow-violet-500/25">
                      <Sparkles className="h-10 w-10 text-white" aria-hidden="true" />
                    </div>
                  </div>
                  <p className="mt-6 text-lg font-bold text-gray-800">Drop an image to detect AI</p>
                  <p className="mt-2 max-w-sm text-center text-sm text-gray-400">
                    Upload any image to check if it was generated by ChatGPT, Midjourney, Gemini, Stable Diffusion or other AI tools
                  </p>
                  <div className="mt-5 flex items-center gap-2 rounded-full bg-violet-100/80 px-5 py-2.5 text-sm font-semibold text-violet-700 transition group-hover:bg-violet-200/80">
                    <Upload className="h-4 w-4" />
                    Browse files
                  </div>
                  <p className="mt-3 text-[11px] text-gray-400">JPEG, PNG, WebP, GIF, BMP — Max 20 MB</p>
                </div>
              )}

              <input ref={fileInputRef} type="file" accept="image/*" onChange={(e) => handleFile(e.target.files?.[0])} className="hidden" />
            </div>

            {imageUrl && (
              <div className="mt-6 flex flex-col items-center gap-4">
                {analyzing && (
                  <div className="w-full max-w-lg">
                    <div className="flex items-center justify-between text-xs font-semibold">
                      <span className="flex items-center gap-1.5 text-gray-500">
                        <Zap className="h-3.5 w-3.5 text-violet-500" />
                        Analysing image…
                      </span>
                      <span className="text-violet-600">{progress}%</span>
                    </div>
                    <div className="mt-2 h-2.5 w-full overflow-hidden rounded-full bg-gray-100">
                      <div
                        className="h-full rounded-full bg-gradient-to-r from-violet-600 via-purple-500 to-fuchsia-500 transition-all duration-300 ease-out"
                        style={{ width: `${progress}%` }}
                      />
                    </div>
                    <div className="mt-2 flex justify-between text-[10px] text-gray-400">
                      <span>Reading metadata</span>
                      <span>FFT analysis</span>
                      <span>Colour stats</span>
                      <span>Noise map</span>
                      <span>Final score</span>
                    </div>
                  </div>
                )}

                <div className="flex gap-3">
                  <button
                    type="button" onClick={analyze} disabled={analyzing}
                    className="inline-flex items-center gap-2.5 rounded-full bg-gradient-to-r from-violet-600 to-purple-600 px-8 py-3 text-sm font-bold text-white shadow-lg shadow-violet-600/25 transition hover:shadow-xl hover:shadow-violet-600/30 hover:brightness-110 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-500 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    {analyzing ? <Loader2 className="h-4 w-4 animate-spin" /> : <ScanEye className="h-4 w-4" />}
                    {analyzing ? "Analysing…" : "Analyse Image"}
                  </button>
                  <button
                    type="button" onClick={reset} disabled={analyzing}
                    className="inline-flex items-center gap-2 rounded-full border border-gray-200 bg-white px-6 py-3 text-sm font-semibold text-gray-600 transition hover:bg-gray-50 hover:border-gray-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400 disabled:opacity-50"
                  >
                    <XCircle className="h-4 w-4" /> Clear
                  </button>
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="p-6 sm:p-10">
            <div className="grid gap-10 lg:grid-cols-12">
              {/* Left: Image + Gauge */}
              <div className="flex flex-col items-center gap-8 lg:col-span-4">
                <div className="relative w-full">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={imageUrl} alt="Analysed" className="w-full rounded-2xl object-contain shadow-xl ring-1 ring-black/5" />
                  <div className="absolute -top-3 -right-3">
                    <span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-bold shadow-lg ${
                      results.overall >= 70 ? "bg-red-500 text-white" : results.overall >= 40 ? "bg-amber-500 text-white" : "bg-emerald-500 text-white"
                    }`}>
                      {results.overall >= 70 ? <AlertTriangle className="h-3 w-3" /> : <CheckCircle2 className="h-3 w-3" />}
                      {results.overall >= 70 ? "AI Detected" : results.overall >= 40 ? "Uncertain" : "Likely Human"}
                    </span>
                  </div>
                </div>

                <GaugeChart score={results.overall} />

                <div className="w-full rounded-2xl border border-gray-100 bg-gradient-to-br from-gray-50 to-violet-50/50 p-5">
                  <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-gray-500">
                    <Camera className="h-3.5 w-3.5" />
                    Top Matches
                  </div>
                  <div className="mt-3 space-y-2.5">
                    {sortedGenerators.slice(0, 3).map((g) => (
                      <GeneratorBar key={g.id} gen={g} score={g.score} />
                    ))}
                  </div>
                </div>
              </div>

              {/* Right: Results */}
              <div className="space-y-7 lg:col-span-8">
                <div>
                  <h3 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-gray-500">
                    <Sparkles className="h-3.5 w-3.5 text-violet-500" />
                    Generator Likelihood
                  </h3>
                  <div className="mt-4 space-y-3">
                    {sortedGenerators.map((g) => (
                      <GeneratorBar key={g.id} gen={g} score={g.score} />
                    ))}
                  </div>
                </div>

                <div className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm">
                  <h3 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-gray-500">
                    <Zap className="h-3.5 w-3.5 text-amber-500" />
                    Analysis Breakdown
                  </h3>
                  <div className="mt-5 space-y-5">
                    {ANALYSIS_METHODS.map((m) => (
                      <AnalysisBar
                        key={m.id}
                        method={m}
                        score={results.methods[m.id]?.score ?? 0}
                        details={results.methods[m.id]?.details}
                      />
                    ))}
                  </div>
                </div>

                <div className="rounded-2xl border border-amber-200 bg-gradient-to-r from-amber-50 to-orange-50 p-5">
                  <p className="flex items-start gap-2.5 text-xs text-amber-700">
                    <Info className="mt-0.5 h-4 w-4 shrink-0" />
                    <span>
                      <strong className="font-semibold">Disclaimer:</strong> This tool provides a probabilistic estimate based on statistical analysis.
                      No detection method is 100% accurate. Results should be used as one signal alongside human judgement.
                      The image is processed entirely in your browser and never uploaded.
                    </span>
                  </p>
                </div>
              </div>
            </div>

            <div className="mt-10 flex justify-center">
              <button
                type="button" onClick={reset}
                className="inline-flex items-center gap-2.5 rounded-full bg-gradient-to-r from-gray-900 to-gray-800 px-8 py-3 text-sm font-bold text-white shadow-lg transition hover:from-gray-800 hover:to-gray-700 hover:shadow-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-500"
              >
                <RefreshCw className="h-4 w-4" />
                Analyse Another Image
              </button>
            </div>
          </div>
        )}

        <div className="border-t border-gray-100 bg-gradient-to-r from-gray-50 to-violet-50/30 px-6 py-5 sm:px-10">
          <p className="flex items-start gap-2.5 text-xs text-gray-500">
            <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-violet-500" />
            <span>
              <strong className="font-semibold">100% private</strong> — your image never leaves your browser.
              All analysis runs locally using Canvas API and JavaScript. Nothing is uploaded, stored or shared.
            </span>
          </p>
        </div>
      </div>
    </div>
  );
};

const AiImageDetector = () => {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  if (!mounted) return null;
  return <AiImageDetectorInner />;
};

export default AiImageDetector;
